### ISSUE TITLE
bug(Unity2022): No overload for method 'BeginBlock' takes 3 arguments 

### ISSUE THREAD

**Issue by douglasduteil** [bguyl/unity-atoms-vs#2]
Bien le bonjour :)

I'm very happy to find this missing piece between UnityAtoms and Unity.VisualScripting 👌  .
Sadly after installing it with a `npx openupm-cli add me.guyl.atoms-vs@2.0.0-preview.1`,  my Unity 2022.1.0a15 project is complaining with :

```
Library\PackageCache\me.guyl.atoms-vs@2.0.0-preview.1\Editor\Utility\UnitButtonInspector.cs(41,13): error CS1501: No overload for method 'BeginBlock' takes 3 arguments
```

After some magic queries, it seems like the API did change both for :
- `com.unity.visualscripting@1.7`
 https://docs.unity3d.com/Packages/com.unity.visualscripting@1.7/api/Unity.VisualScripting.Inspector.html?q=Inspector#Unity_VisualScripting_Inspector_BeginBlock_Unity_VisualScripting_Metadata_Rect_
- `Bolt@1.4` https://docs.unity3d.com/bolt/1.4/api/Ludiq.Inspector.html#Ludiq_Inspector_BeginBlock_Ludiq_Accessor_Rect_

I'll try some local fixing, but a new _preview_ release will be welcome, if you have the time for it :)

Merci 🥖

**Comment by bguyl** [comment]
Thanks for the information and the PR 👍 
Fixed for version 2.0.0
